### ISSUE TITLE
help with installing another app

### ISSUE THREAD

**Issue by yonicd** [Tutuchan/slackrdoc#1]
how did you set up the oath redirect? i have tried it for an app i made and cant get it to work. the slack documentation doesnt give enough info for newbie users.

thanks!

cc @hrbrmstr

**Comment by Tutuchan** [comment]
Wow, I'm sorry, I did not see this issue until today.

To be honest, I used this [Slack tutorial](https://github.com/slackapi/Slack-Python-Onboarding-Tutorial) and the auth part was already implemented so I did not change anything. I hope that helps you.

**Comment by yonicd** [comment]
thank you! i'll try to follow that link.
